### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by ARFauzi24** [88sparesinternship/data_karyawan_app#18]
ka @Keda87 , pas **python manage.py migrate** yang di models.py ga masuk ke database sqlitenya

**Comment by Keda87** [comment]
@noiras gimana cara taunya kalo models nya gak masuk ke database sqlite nya?

**Comment by ARFauzi24** [comment]
@Keda87 udah download db browser sqlite ka jadi ketauan

**Comment by ARFauzi24** [comment]
@Keda87 done ka, udah bisa
