### ISSUE TITLE
as_view

### ISSUE THREAD

**Issue by ARFauzi24** [88sparesinternship/data_karyawan_app#20]
ka @Keda87  fungsi as_view di urls apa ya ka?

**Comment by Keda87** [comment]
django `url` atau `path` di argumen ke 2 hanya menerima fungsi.
Sedangkan django view yg menggunakan class harus menggunakan `as_view` untuk bisa memanggil view nya.

https://docs.djangoproject.com/en/2.0/topics/class-based-views/intro/#using-class-based-views
